#!/usr/bin/env perl
#-*-perl-*-
#
#

## make this a module
package ISO::639::5;

# use 5.006;
use strict;
use warnings;

use utf8;
use open ':locale';
use Pod::Usage;
use ISO::639::3;

=head1 NAME

ISO::639::5 - Language groups

=head1 VERSION

Version 0.01

=cut

our $VERSION      = '0.01';

use Exporter 'import';
our @EXPORT = qw(
    language_group
    language_parent
);
our %EXPORT_TAGS = ( all => \@EXPORT );


=head1 SYNOPSIS

    use ISO::639::5 qw/:all/;

=cut

our $LanguageGroup;
our $LanguageParent;

$LanguageGroup = {
  'taw' => [
    'lao',
    'tha'
  ],
  'oto' => [
    'otm'
  ],
  'cel' => [
    'bre',
    'cym',
    'gle',
    'gla',
    'glv',
    'cor',
    'mga',
    'nrc',
    'obt',
    'owl',
    'sga',
    'wlm',
    'xbm',
    'xcb',
    'xce',
    'xga',
    'xpi'
  ],
  'pqe' => [
    'agw',
    'ahb',
    'aia',
    'aie',
    'aji',
    'akr',
    'alm',
    'alu',
    'ane',
    'anx',
    'apb',
    'app',
    'apr',
    'asz',
    'aty',
    'aua',
    'aud',
    'aul',
    'auq',
    'aut',
    'baa',
    'bch',
    'bcm',
    'bcu',
    'bgt',
    'bhc',
    'bhw',
    'biq',
    'bjk',
    'blp',
    'blq',
    'bnk',
    'bnr',
    'bpa',
    'brr',
    'btr',
    'buk',
    'bvc',
    'bvd',
    'bwd',
    'bxa',
    'bxf',
    'bzh',
    'bzq',
    'cal',
    'cam',
    'chk',
    'crc',
    'ddi',
    'dgg',
    'dhv',
    'dob',
    'dor',
    'kzk',
    'erg',
    'erk',
    'etn',
    'faf',
    'far',
    'fij',
    'frt',
    'fud',
    'fut',
    'fwa',
    'gdd',
    'gei',
    'gfk',
    'gga',
    'ggt',
    'ghn',
    'gil',
    'kzk',
    'gmb',
    'goo',
    'gri',
    'grz',
    'gzn',
    'hah',
    'hao',
    'haw',
    'hiw',
    'hla',
    'hoa',
    'hrw',
    'iai',
    'irh',
    'jae',
    'jaj',
    'jaz',
    'kbm',
    'kdk',
    'khl',
    'kij',
    'kji',
    'kkk',
    'klv',
    'koa',
    'kos',
    'kpg',
    'kqw',
    'krf',
    'ksd',
    'ksg',
    'ktm',
    'kvc',
    'kwd',
    'kwf',
    'kxr',
    'kzk',
    'kzu',
    'lbb',
    'lbv',
    'lcm',
    'lek',
    'ler',
    'leu',
    'lga',
    'lgb',
    'lgk',
    'lgl',
    'lgr',
    'lgu',
    'lht',
    'lib',
    'lid',
    'lkn',
    'lle',
    'llf',
    'llp',
    'llu',
    'llx',
    'lmg',
    'lml',
    'lmu',
    'lmv',
    'loj',
    'los',
    'lpa',
    'lrv',
    'lrz',
    'lww',
    'mee',
    'mek',
    'met',
    'meu',
    'mft',
    'mgl',
    'mah',
    'mri',
    'mkj',
    'mkv',
    'mky',
    'mla',
    'mln',
    'mlu',
    'mlv',
    'mme',
    'mmg',
    'mmt',
    'mmw',
    'mmx',
    'mna',
    'mnv',
    'mox',
    'mpr',
    'mpy',
    'mqa',
    'mqm',
    'mrb',
    'mrl',
    'mrm',
    'mrn',
    'mrq',
    'mrv',
    'msq',
    'mte',
    'mtt',
    'mvo',
    'mwc',
    'mwh',
    'mwi',
    'mwo',
    'mxe',
    'nau',
    'nal',
    'ncc',
    'ncf',
    'ncn',
    'nee',
    'nem',
    'nqn',
    'nfl',
    'ngr',
    'niu',
    'nke',
    'nkr',
    'nlg',
    'nmb',
    'nmk',
    'nms',
    'nmt',
    'nnd',
    'npn',
    'nsn',
    'nss',
    'nsw',
    'nua',
    'nuw',
    'nwi',
    'olr',
    'omb',
    'onu',
    'ora',
    'pek',
    'pex',
    'pfa',
    'pgk',
    'pif',
    'piv',
    'piz',
    'pkg',
    'pma',
    'pme',
    'pmt',
    'pnh',
    'pon',
    'pop',
    'ppn',
    'pri',
    'pss',
    'psw',
    'ptp',
    'ptv',
    'puw',
    'pwg',
    'rai',
    'rak',
    'rap',
    'rar',
    'ray',
    'roe',
    'rri',
    'rro',
    'rug',
    'sax',
    'sbb',
    'sbc',
    'sbe',
    'sbh',
    'sgz',
    'sij',
    'sjr',
    'sku',
    'slz',
    'smo',
    'sns',
    'sob',
    'sol',
    'sov',
    'sps',
    'ssg',
    'stn',
    'stw',
    'swp',
    'szw',
    'tbc',
    'tbe',
    'tbf',
    'tbj',
    'tgc',
    'tgi',
    'tgp',
    'tgs',
    'tio',
    'tkl',
    'tkp',
    'tkw',
    'tlm',
    'tlr',
    'tlx',
    'tmb',
    'tmi',
    'tmy',
    'tnk',
    'tnl',
    'tnn',
    'tnp',
    'tnx',
    'ton',
    'tox',
    'tpv',
    'tpz',
    'tql',
    'tqp',
    'tsr',
    'ttu',
    'ttv',
    'tuc',
    'tva',
    'tvk',
    'tvl',
    'twp',
    'tah',
    'ubr',
    'uge',
    'uli',
    'upv',
    'urr',
    'urv',
    'utp',
    'uve',
    'uvl',
    'vao',
    'vmg',
    'vnk',
    'vnm',
    'vra',
    'vrs',
    'vrt',
    'wiv',
    'wls',
    'woe',
    'wuv',
    'wwo',
    'wyy',
    'xsi',
    'yap',
    'yly',
    'zgr'
  ],
  'khi' => [
    'hts',
    'ktz',
    'kwz',
    'naq',
    'nmn',
    'sad'
  ],
  'phi' => [
    'akl',
    'bik',
    'blf',
    'bno',
    'bnq',
    'ceb',
    'cps',
    'fil',
    'gqr',
    'hil',
    'ibg',
    'ibl',
    'ify',
    'ilk',
    'ilo',
    'kak',
    'krj',
    'kyj',
    'kyk',
    'loc',
    'mdh',
    'mno',
    'mog',
    'mrw',
    'msb',
    'pag',
    'pmn',
    'rth',
    'sgd',
    'snl',
    'sxn',
    'tbl',
    'tdn',
    'kak',
    'tnt',
    'tnw',
    'tom',
    'txs',
    'war'
  ],
  'csu' => [
    'avu',
    'bdh',
    'bex',
    'bot',
    'kcm',
    'led',
    'mdi',
    'mdj',
    'mhi',
    'mwm',
    'myb',
    'niy',
    'sba'
  ],
  'iir' => [
    'ask',
    'bsh',
    'inc',
    'ira',
    'prn',
    'wbk',
    'xvi'
  ],
  'xgn' => [
    'bub',
    'dta',
    'kxs',
    'mhj',
    'mjg',
    'mon',
    'mvf',
    'peh',
    'sce',
    'xal',
    'xwo',
    'yuy'
  ],
  'gem' => [
    'gme',
    'gmq',
    'gmw'
  ],
  'jpx' => [
    'jpn'
  ],
  'iro' => [
    'cay',
    'chr',
    'lre',
    'moh',
    'ntw',
    'one',
    'ons',
    'see',
    'sqn',
    'tus',
    'wya'
  ],
  'kar' => [
    'kvq'
  ],
  'ira' => [
    'ave',
    'bal',
    'bsg',
    'ckb',
    'fas',
    'glk',
    'hac',
    'haz',
    'isk',
    'jdt',
    'jpr',
    'kho',
    'kur',
    'lrc',
    'lsa',
    'mzn',
    'oru',
    'oss',
    'abw',
    'peo',
    'prc',
    'pus',
    'sgh',
    'sgl',
    'sgy',
    'siy',
    'smy',
    'sog',
    'sqo',
    'srh',
    'tgk',
    'tly',
    'ttt',
    'wbl',
    'xbc',
    'xco',
    'xpr',
    'xsc',
    'yai',
    'zum',
    'zza'
  ],
  'sla' => [
    'zle',
    'zls',
    'zlw'
  ],
  'trk' => [
    'aib',
    'alt',
    'aze',
    'azb',
    'bak',
    'chg',
    'cjs',
    'clw',
    'crh',
    'chv',
    'dlg',
    'gag',
    'ili',
    'jct',
    'kaa',
    'kdr',
    'kia',
    'kjh',
    'kaz',
    'klj',
    'kmz',
    'krc',
    'kum',
    'kir',
    'ota',
    'otk',
    'qwm',
    'qxq',
    'sah',
    'slr',
    'tuk',
    'tur',
    'tat',
    'tyv',
    'uig',
    'uzb',
    'uzs',
    'xpc',
    'ybe'
  ],
  'grk' => [
    'cpg',
    'ell',
    'gmy',
    'grc',
    'pnt',
    'tsd',
    'yej'
  ],
  'aav' => [
    'irr',
    'kdt',
    'mkh',
    'mun',
    'nyl',
    'sss',
    'tth'
  ],
  'nah' => [
    'nci'
  ],
  'dra' => [
    'brh',
    'gon',
    'iru',
    'kfa',
    'kfc',
    'kff',
    'kmj',
    'kan',
    'kru',
    'kru',
    'kxu',
    'kxv',
    'mjt',
    'mjv',
    'mal',
    'muv',
    'tam',
    'tcx',
    'tcy',
    'tel'
  ],
  'gmq' => [
    'dan',
    'fao',
    'isl',
    'nob',
    'nno',
    'non',
    'nrn',
    'ovd',
    'rmg',
    'swe'
  ],
  'ngb' => [
    'sag'
  ],
  'bat' => [
    'lit',
    'ltg',
    'lav',
    'ndf',
    'olt',
    'prg',
    'sgs',
    'svx',
    'sxl',
    'xcu',
    'xgl',
    'xsv',
    'xzm'
  ],
  'urj' => [
    'fiu',
    'syd'
  ],
  'cpf' => [
    'acf',
    'cks',
    'crs',
    'gcf',
    'gcr',
    'hat',
    'kmv',
    'loj',
    'mfe',
    'rcf'
  ],
  'fiu' => [
    'chm',
    'est',
    'fin',
    'fit',
    'fkv',
    'hun',
    'izh',
    'kca',
    'kkt',
    'krl',
    'kom',
    'liv',
    'mdf',
    'mns',
    'mrj',
    'myv',
    'ong',
    'smi',
    'udm',
    'vep',
    'vot',
    'vro'
  ],
  'afa' => [
    'ber',
    'bxe',
    'cdc',
    'cop',
    'cus',
    'egy',
    'omv',
    'sem',
    'zwa'
  ],
  'ypk' => [
    'ems',
    'ess',
    'esu',
    'ynk'
  ],
  'ngf' => [
    'bjz',
    'ekg',
    'uhn'
  ],
  'map' => [
    'fox',
    'lcl',
    'lnd',
    'poz'
  ],
  'syd' => [
    'mtm',
    'nio',
    'sel',
    'xas',
    'yrk'
  ],
  'ath' => [
    'aht',
    'apa',
    'bcr',
    'bea',
    'caf',
    'chp',
    'clc',
    'crx',
    'den',
    'dgr',
    'gwi',
    'haa',
    'hup',
    'ing',
    'kkz',
    'koy',
    'kuu',
    'srs',
    'tau',
    'tcb',
    'tgx',
    'tht',
    'jic'
  ],
  'ber' => [
    'cnu',
    'grr',
    'jbe',
    'jbn',
    'kab',
    'mzb',
    'nxm',
    'oua',
    'rif',
    'sds',
    'shr',
    'shy',
    'siz',
    'taq',
    'thv',
    'tmh',
    'tzm',
    'zen',
    'zgh'
  ],
  'bnt' => [
    'abb',
    'asa',
    'auh',
    'bas',
    'beb',
    'bem',
    'beq',
    'bez',
    'bip',
    'bja',
    'bkh',
    'bkw',
    'bng',
    'bni',
    'bqz',
    'brf',
    'btb',
    'bmv',
    'bvb',
    'bwt',
    'bxg',
    'cgg',
    'cjk',
    'cwe',
    'dav',
    'dez',
    'dma',
    'dua',
    'ebu',
    'eko',
    'eto',
    'ewo',
    'fan',
    'fip',
    'guz',
    'haq',
    'heh',
    'hke',
    'hoo',
    'her',
    'jmc',
    'kdx',
    'kck',
    'kcv',
    'kde',
    'kon',
    'kik',
    'kua',
    'kkj',
    'kmb',
    'koo',
    'koq',
    'kqn',
    'ksb',
    'ksf',
    'kws',
    'kzo',
    'lag',
    'lch',
    'lug',
    'lik',
    'lin',
    'lol',
    'loz',
    'lub',
    'lua',
    'lue',
    'lun',
    'luy',
    'lyn',
    'mbo',
    'mdw',
    'mnu',
    'mgh',
    'mhb',
    'mhw',
    'mye',
    'nba',
    'nde',
    'ndc',
    'ndo',
    'ngc',
    'ngl',
    'njx',
    'nmg',
    'nnb',
    'nbl',
    'nse',
    'nso',
    'nya',
    'nyf',
    'nym',
    'nyn',
    'pic',
    'run',
    'rng',
    'rof',
    'kin',
    'rwk',
    'rwm',
    'sbp',
    'seh',
    'shr',
    'sna',
    'snq',
    'urw',
    'ssw',
    'sot',
    'suk',
    'swa',
    'swb',
    'tll',
    'tsn',
    'toi',
    'tso',
    'tum',
    'umb',
    'ven',
    'vif',
    'vmk',
    'vun',
    'wdd',
    'wlc',
    'wni',
    'xho',
    'xog',
    'yao',
    'zdj',
    'zmw',
    'zul'
  ],
  'bai' => [
    'bbj',
    'bko',
    'byv',
    'fmp',
    'jgo',
    'nla',
    'nnh',
    'nnz',
    'nwe',
    'xmg',
    'ybb'
  ],
  'gmw' => [
    'afr',
    'ang',
    'cim',
    'deu',
    'dum',
    'eng',
    'enm',
    'frk',
    'frr',
    'fry',
    'gct',
    'gmh',
    'gml',
    'goh',
    'gos',
    'gsw',
    'ksh',
    'ltz',
    'lim',
    'lng',
    'mhn',
    'nds',
    'nld',
    'odt',
    'ofs',
    'osx',
    'pdc',
    'pfl',
    'sco',
    'stq',
    'swg',
    'wae',
    'wep',
    'wym',
    'yec',
    'yid',
    'zea'
  ],
  'pra' => [
    'pli',
    'san'
  ],
  'cus' => [
    'aar',
    'arv',
    'bej',
    'bji',
    'byn',
    'dal',
    'irk',
    'orm',
    'orc',
    'sid',
    'som',
    'ssn',
    'ssy'
  ],
  'zhx' => [
    'cdo',
    'cjy',
    'cpx',
    'czh',
    'czo',
    'gan',
    'hak',
    'hsn',
    'ltc',
    'mnp',
    'nan',
    'och',
    'wuu',
    'wxa',
    'yue',
    'zho'
  ],
  'azc' => [
    'chl',
    'com',
    'cup',
    'hch',
    'hop',
    'lui',
    'mfy',
    'mnr',
    'nah',
    'ntp',
    'ood',
    'opt',
    'pao',
    'par',
    'pia',
    'ppl',
    'ser',
    'shh',
    'stp',
    'tac',
    'tar',
    'tla',
    'tub',
    'var',
    'xaw',
    'xgf',
    'yaq'
  ],
  'wen' => [
    'dsb',
    'hsb'
  ],
  'art' => [
    'afh',
    'avk',
    'bzt',
    'dws',
    'epo',
    'ina',
    'ile',
    'igs',
    'ido',
    'jbo',
    'ldn',
    'lfn',
    'neu',
    'nov',
    'qya',
    'rmv',
    'sjn',
    'tlh',
    'tzl',
    'vol',
    'zbl'
  ],
  'fox' => [
    'bnn',
    'bzg',
    'ckv',
    'dru',
    'fos',
    'pwn',
    'pyu',
    'ssf',
    'sxr',
    'tay',
    'trv',
    'tsu',
    'uun',
    'xnb',
    'xsy'
  ],
  'alv' => [
    'aba',
    'abi',
    'abr',
    'ado',
    'ada',
    'adj',
    'agq',
    'ajg',
    'aka',
    'anw',
    'atk',
    'avi',
    'ayb',
    'azo',
    'bad',
    'bai',
    'bax',
    'bba',
    'bce',
    'bci',
    'bda',
    'beh',
    'bfd',
    'bfl',
    'bgj',
    'bim',
    'bin',
    'bju',
    'bkc',
    'bkm',
    'blo',
    'bmq',
    'bnt',
    'bqj',
    'bsc',
    'cae',
    'cou',
    'cwt',
    'dag',
    'dij',
    'dop',
    'dur',
    'dyo',
    'ebr',
    'ewe',
    'efi',
    'fap',
    'ful',
    'fod',
    'fon',
    'ttb',
    'gba',
    'gej',
    'gjn',
    'gkn',
    'goy',
    'gur',
    'gux',
    'ibo',
    'ijo',
    'jab',
    'kbp',
    'kcj',
    'kdh',
    'keu',
    'kia',
    'kma',
    'knf',
    'kqs',
    'kro',
    'krx',
    'kss',
    'kzc',
    'kzr',
    'ldm',
    'lee',
    'lmp',
    'lob',
    'mdd',
    'mfq',
    'mfv',
    'mgo',
    'mlo',
    'mnh',
    'mor',
    'mos',
    'mql',
    'mua',
    'myk',
    'mzm',
    'mzv',
    'mzw',
    'naj',
    'ndv',
    'nfr',
    'nga',
    'ngb',
    'nie',
    'nku',
    'ntm',
    'nza',
    'nzi',
    'ogc',
    'oku',
    'otr',
    'ozm',
    'pbo',
    'pbp',
    'pil',
    'pny',
    'pug',
    'sav',
    'sev',
    'shz',
    'snf',
    'soy',
    'spp',
    'srr',
    'tbz',
    'kdh',
    'tfi',
    'tik',
    'tiv',
    'tkq',
    'tnr',
    'tui',
    'tuz',
    'urh',
    'wci',
    'wol',
    'wwa',
    'xsm',
    'xwe',
    'yav',
    'yky',
    'yor'
  ],
  'poz' => [
    'aol',
    'bhp',
    'end',
    'hvn',
    'ivv',
    'kei',
    'kvh',
    'mqy',
    'nxe',
    'ple',
    'plf',
    'pqe',
    'pqw',
    'ski',
    'tao',
    'xbr',
    'xxk'
  ],
  'sit' => [
    'dzo',
    'ero',
    'grt',
    'hmr',
    'hni',
    'iii',
    'jkr',
    'kac',
    'kar',
    'lbj',
    'lus',
    'mni',
    'mya',
    'new',
    'njh',
    'njm',
    'nmy',
    'nwc',
    'nxq',
    'qvy',
    'sxg',
    'tbq',
    'tsj',
    'txg',
    'xsr',
    'zhx'
  ],
  'euq' => [
    'eus'
  ],
  'mun' => [
    'hoc',
    'pcj',
    'sat',
    'unr'
  ],
  'hmx' => [
    'bje',
    'bpn',
    'buh',
    'bwn',
    'cqd',
    'hmd',
    'hml',
    'hmn',
    'hnj',
    'ium',
    'mji',
    'mmr',
    'mww',
    'pha',
    'pnu',
    'shx'
  ],
  'sgn' => [
    'csn',
    'fcs',
    'fsl',
    'ils',
    'isg',
    'rsl'
  ],
  'aqa' => [
    'alc'
  ],
  'itc' => [
    'lat',
    'osc',
    'roa',
    'spx',
    'xfa',
    'xum'
  ],
  'pqw' => [
    'abl',
    'abs',
    'abx',
    'ban',
    'bdg',
    'bdl',
    'bdr',
    'beg',
    'bew',
    'bjn',
    'bkz',
    'bsu',
    'btk',
    'buc',
    'bug',
    'cha',
    'cia',
    'cmc',
    'dai',
    'dbj',
    'drg',
    'dtr',
    'dun',
    'dup',
    'duq',
    'duw',
    'eno',
    'gay',
    'goq',
    'iba',
    'ind',
    'jav',
    'kaw',
    'kge',
    'kjc',
    'kjk',
    'kqr',
    'ktq',
    'kvr',
    'kxd',
    'kyi',
    'kys',
    'lbw',
    'lbx',
    'lce',
    'lcf',
    'ley',
    'liw',
    'ljp',
    'llk',
    'mad',
    'mak',
    'mdr',
    'mfa',
    'mfb',
    'mlg',
    'mhy',
    'min',
    'mkm',
    'mqn',
    'msa',
    'mtd',
    'mui',
    'mwv',
    'mxr',
    'myl',
    'mzq',
    'nia',
    'nij',
    'nrm',
    'otd',
    'pau',
    'pdo',
    'pel',
    'phi',
    'pku',
    'pse',
    'raz',
    'ree',
    'rej',
    'sas',
    'sda',
    'sjm',
    'skh',
    'slm',
    'sml',
    'smr',
    'smw',
    'snv',
    'ssb',
    'sse',
    'sun',
    'sya',
    'tdi',
    'dtp',
    'tdx',
    'tjg',
    'tkg',
    'tlk',
    'twy',
    'txy',
    'ulu',
    'vkl',
    'vko',
    'wow',
    'wru',
    'xkq',
    'xmv',
    'xmw',
    'xmz',
    'yka',
    'zbc',
    'zbe',
    'zbw'
  ],
  'cmc' => [
    'ace',
    'cje',
    'cjm',
    'hro',
    'huq',
    'jra',
    'rad',
    'rog'
  ],
  'cba' => [
    'bzd',
    'cbg',
    'chb',
    'kog',
    'mbp',
    'mot',
    'tuf'
  ],
  'cpp' => [
    'aoa',
    'cri',
    'fab',
    'kea',
    'mzs',
    'pap',
    'pov',
    'pre',
    'srm',
    'xmm'
  ],
  'omq' => [
    'cco',
    'coz',
    'czn',
    'ixc',
    'maj',
    'maq',
    'miz',
    'mxb',
    'oto',
    'pbs',
    'pmq',
    'pmz',
    'tpc',
    'tpl',
    'tpx',
    'trs',
    'zap',
    'zaw',
    'ztq',
    'zty'
  ],
  'aql' => [
    'alg',
    'wiy',
    'yur'
  ],
  'mul' => [
    'aav',
    'afa',
    'aqa',
    'aql',
    'art',
    'auf',
    'aus',
    'awd',
    'azc',
    'cau',
    'cba',
    'cdd',
    'dra',
    'esx',
    'euq',
    'hmx',
    'hok',
    'ine',
    'iro',
    'jpx',
    'khi',
    'map',
    'myn',
    'nic',
    'omq',
    'paa',
    'sal',
    'sgn',
    'xsi',
    'sit',
    'ssa',
    'taw',
    'tup',
    'tut',
    'urj',
    'wak',
    'xnd'
  ],
  'sdv' => [
    'ach',
    'alz',
    'anu',
    'bfa',
    'ddd',
    'din',
    'enb',
    'eyo',
    'kdj',
    'keo',
    'kln',
    'kpz',
    'lky',
    'lot',
    'lpx',
    'luo',
    'mas',
    'mqu',
    'muz',
    'niq',
    'nsg',
    'nub',
    'nus',
    'saq',
    'sgc',
    'shk',
    'tec',
    'teo',
    'toq',
    'tuv',
    'tuy'
  ],
  'tut' => [
    'nog',
    'trk',
    'tuw',
    'xgn'
  ],
  'dmn' => [
    'bib',
    'bam',
    'bqc',
    'dnj',
    'dyu',
    'goa',
    'kax',
    'knk',
    'kno',
    'knu',
    'kpe',
    'lom',
    'man',
    'men',
    'mlq',
    'moa',
    'mwk',
    'rkm',
    'snk',
    'sus',
    'vai',
    'xkg',
    'yal'
  ],
  'gme' => [
    'got',
    'xvn'
  ],
  'nic' => [
    'alv',
    'dmn',
    'eka',
    'kdo',
    'lam',
    'nqo',
    'nyo',
    'tog',
    'znd'
  ],
  'dai' => [
    'bth',
    'lra',
    'sdo',
    'sne'
  ],
  'cdd' => [
    'aac',
    'cad',
    'kii',
    'paw',
    'wic'
  ],
  'zls' => [
    'bul',
    'bos',
    'chu',
    'hrv',
    'mkd',
    'slv',
    'srp'
  ],
  'alg' => [
    'alq',
    'arp',
    'atj',
    'ats',
    'bla',
    'chy',
    'ciw',
    'cre',
    'del',
    'kic',
    'mez',
    'mia',
    'mic',
    'mjy',
    'moe',
    'nnt',
    'oji',
    'ojs',
    'ojw',
    'otw',
    'pim',
    'pot',
    'qyp',
    'sac',
    'sjw',
    'unm',
    'wam',
    'xlb',
    'xlo',
    'xnt',
    'xpq'
  ],
  'ccs' => [
    'kat',
    'lzz',
    'sva',
    'xmf'
  ],
  'kro' => [
    'ald',
    'bsq',
    'dic',
    'grb',
    'gud',
    'gxx',
    'ney',
    'nwb',
    'wec'
  ],
  'ccn' => [
    'abk',
    'abq',
    'ady',
    'agx',
    'akv',
    'ani',
    'aqc',
    'ava',
    'bbl',
    'bdk',
    'bph',
    'che',
    'cji',
    'dar',
    'ddo',
    'gdo',
    'gin',
    'huz',
    'inh',
    'ykm',
    'kbd',
    'khv',
    'kjj',
    'kpt',
    'kry',
    'kva',
    'lbe',
    'lez',
    'rut',
    'tab',
    'tin',
    'tkr',
    'uby',
    'udi'
  ],
  'xsi' => [
    'asb',
    'bll',
    'cro',
    'dak',
    'hid',
    'iow',
    'ksk',
    'lkt',
    'mhq',
    'ofo',
    'oma',
    'osa',
    'qua',
    'sto',
    'tta',
    'win',
    'xwc'
  ],
  'cdc' => [
    'anc',
    'ank',
    'bid',
    'daa',
    'hau',
    'hed',
    'lme',
    'maf',
    'mcn',
    'mmy',
    'mpz',
    'mse',
    'mug',
    'nnc',
    'nnn',
    'pip',
    'sor',
    'tmc',
    'zim',
    'zuy'
  ],
  'auf' => [
    'aru',
    'cul',
    'dny',
    'pad',
    'swx'
  ],
  'tup' => [
    'eme',
    'grn',
    'gui',
    'guq',
    'gyr',
    'kay',
    'kgk',
    'kpn',
    'ktn',
    'kyr',
    'mpu',
    'myu',
    'nhd',
    'psm',
    'skf',
    'srq',
    'tpj',
    'tpr',
    'tpw',
    'twt',
    'wyr',
    'yrl'
  ],
  'apa' => [
    'apj',
    'apk',
    'apl',
    'apw',
    'nav'
  ],
  'sem' => [
    'aao',
    'acw',
    'acy',
    'aeb',
    'afb',
    'aii',
    'ajt',
    'akk',
    'amh',
    'amw',
    'apc',
    'ara',
    'arc',
    'arq',
    'ary',
    'arz',
    'ayl',
    'gdq',
    'gez',
    'har',
    'heb',
    'jrb',
    'mey',
    'mlt',
    'phn',
    'snx',
    'shu',
    'smp',
    'sqr',
    'syc',
    'tir',
    'tig',
    'tmr',
    'uga',
    'xaa',
    'xeb',
    'xpu'
  ],
  'smi' => [
    'sme',
    'sia',
    'sjd',
    'sje',
    'sjt',
    'sma',
    'smj',
    'smn',
    'sms'
  ],
  'zle' => [
    'bel',
    'orv',
    'rus',
    'rue',
    'ukr'
  ],
  'mkh' => [
    'bbh',
    'bgk',
    'blr',
    'caq',
    'cbn',
    'crv',
    'cwg',
    'huo',
    'jah',
    'jhi',
    'kha',
    'kjg',
    'khm',
    'lbn',
    'mhe',
    'mlf',
    'mml',
    'mnw',
    'mqt',
    'mra',
    'mtq',
    'ncb',
    'oyb',
    'ply',
    'prk',
    'prt',
    'rka',
    'scb',
    'sea',
    'sii',
    'tef',
    'tnz',
    'tpu',
    'tyh',
    'uuu',
    'vie',
    'vwa',
    'wbm',
    'xao',
    'xnh',
    'zng'
  ],
  'xnd' => [
    'ath',
    'eya',
    'hoi',
    'tfn',
    'tli'
  ],
  'znd' => [
    'zne'
  ],
  'myn' => [
    'acr',
    'agu',
    'caa',
    'cac',
    'cak',
    'ctu',
    'hus',
    'itz',
    'ixl',
    'jac',
    'kek',
    'kjb',
    'knj',
    'mam',
    'mhc',
    'mop',
    'poc',
    'poh',
    'quc',
    'qum',
    'quv',
    'toj',
    'ttc',
    'tzh',
    'tzj',
    'tzo',
    'usp',
    'yua'
  ],
  'aus' => [
    'bck',
    'dbl',
    'ddj',
    'gbu',
    'gni',
    'kdd',
    'kjn',
    'kld',
    'mep',
    'nha',
    'nuy',
    'pix',
    'pkn',
    'vma',
    'vmb',
    'wbp',
    'wmt',
    'xbp',
    'xrg',
    'yii',
    'yij'
  ],
  'swa' => [
    'swc'
  ],
  'son' => [
    'ddn',
    'dje',
    'kcy',
    'khq',
    'ses',
    'twq'
  ],
  'sal' => [
    'cjh',
    'clm',
    'liw',
    'coo',
    'cow',
    'crd',
    'fla',
    'hur',
    'lil',
    'nok',
    'oka',
    'qun',
    'shs',
    'spo',
    'squ',
    'str',
    'thp'
  ],
  'ine' => [
    'aln',
    'anp',
    'bat',
    'cel',
    'cms',
    'gem',
    'grk',
    'hit',
    'hlu',
    'hye',
    'iir',
    'imy',
    'itc',
    'plq',
    'scx',
    'sdt',
    'sla',
    'sqi',
    'txb',
    'txh',
    'xcl',
    'xcr',
    'xdc',
    'xlc',
    'xld',
    'xlg',
    'xls',
    'xmk',
    'xpg',
    'xps',
    'xsd',
    'xto',
    'xve'
  ],
  'esx' => [
    'ale',
    'ipk',
    'iku',
    'kal',
    'ypk',
    'ysr'
  ],
  'cau' => [
    'ccn',
    'ccs'
  ],
  'tuw' => [
    'eve',
    'evn',
    'gld',
    'juc',
    'mnc',
    'neg',
    'oaa',
    'oac',
    'orh',
    'sjo',
    'ude',
    'ulc'
  ],
  'zlw' => [
    'ces',
    'csb',
    'czk',
    'pol',
    'pox',
    'slk',
    'szl',
    'wen'
  ],
  'hok' => [
    'acv',
    'atw',
    'boi',
    'cid',
    'coc',
    'crz',
    'esq',
    'inz',
    'kju',
    'klb',
    'kyh',
    'mov',
    'mrc',
    'obi',
    'peb',
    'pef',
    'pej',
    'peq',
    'pmo',
    'poo',
    'ppi',
    'puy',
    'sei',
    'sht',
    'sln',
    'veo',
    'was',
    'ynn',
    'yuf',
    'yum'
  ],
  'btk' => [
    'akb',
    'bbc',
    'btd',
    'btm',
    'bts',
    'btx',
    'btz'
  ],
  'ssa' => [
    'csu',
    'dzg',
    'fvr',
    'gly',
    'guk',
    'ikx',
    'kbl',
    'kie',
    'kmq',
    'kau',
    'lgn',
    'mde',
    'mls',
    'rou',
    'sdv',
    'son',
    'teu',
    'tuq',
    'udu',
    'wti',
    'xmr',
    'xom'
  ],
  'wak' => [
    'dtd',
    'has',
    'hei',
    'kwk',
    'myh',
    'noc'
  ],
  'inc' => [
    'asm',
    'awa',
    'bgc',
    'bhb',
    'bho',
    'bjj',
    'bkk',
    'ben',
    'bns',
    'bpy',
    'bra',
    'ccp',
    'ctg',
    'dml',
    'doi',
    'div',
    'emx',
    'guj',
    'gwc',
    'gwt',
    'hin',
    'hif',
    'hne',
    'khw',
    'kls',
    'kok',
    'kas',
    'lah',
    'mag',
    'mai',
    'mar',
    'mvy',
    'mwr',
    'nep',
    'ori',
    'pan',
    'phl',
    'pra',
    'raj',
    'rml',
    'rmq',
    'rmt',
    'rom',
    'scl',
    'snd',
    'sdg',
    'sin',
    'skr',
    'syl',
    'urd'
  ],
  'nub' => [
    'fia',
    'onw'
  ],
  'roa' => [
    'arg',
    'ast',
    'cat',
    'cos',
    'cpf',
    'cpp',
    'dlm',
    'egl',
    'spa',
    'ext',
    'fax',
    'fra',
    'frc',
    'frm',
    'fro',
    'frp',
    'fvr',
    'glg',
    'ist',
    'ita',
    'lad',
    'lij',
    'lld',
    'lmo',
    'mwl',
    'mxi',
    'nap',
    'nrf',
    'oci',
    'osp',
    'pcd',
    'pms',
    'por',
    'rgn',
    'roh',
    'ron',
    'ruo',
    'rup',
    'ruq',
    'srd',
    'scn',
    'sdc',
    'sdn',
    'vec',
    'wln'
  ],
  'paa' => [
    'aau',
    'anz',
    'ddg',
    'gak',
    'kax',
    'kmo',
    'lvk',
    'mqt',
    'nas',
    'ngf',
    'pgu',
    'saj',
    'tcm',
    'tft',
    'tif',
    'tlb',
    'tqu',
    'waj',
    'wli',
    'yee',
    'zuh'
  ],
  'plf' => [
    'alo',
    'amv',
    'gap',
    'hbu',
    'kje',
    'lti',
    'mhs',
    'szn',
    'tet',
    'tlv',
    'txn',
    'wha'
  ],
  'tbq' => [
    'adx',
    'anm',
    'bod',
    'bqh',
    'brx',
    'duu',
    'ers',
    'gqi',
    'gro',
    'jya',
    'lhu',
    'lpo',
    'mxj',
    'njo',
    'nun',
    'trp',
    'twm'
  ],
  'omv' => [
    'aiw',
    'bcq',
    'bwo',
    'dim',
    'doz',
    'jnj',
    'mdx',
    'noz',
    'shx',
    'wal',
    'zwa'
  ],
  'awd' => [
    'aca',
    'ame',
    'apu',
    'bae',
    'brg',
    'ccc',
    'cui',
    'gob',
    'guc',
    'guh',
    'guo',
    'ign',
    'inp',
    'kpc',
    'mbn',
    'not',
    'pbg',
    'pib',
    'pio',
    'plu',
    'tae',
    'trn',
    'ycn'
  ]
};
$LanguageParent = {
  'sgy' => 'ira',
  'ban' => 'pqw',
  'oss' => 'ira',
  'lrv' => 'pqe',
  'jpr' => 'ira',
  'hoc' => 'mun',
  'lek' => 'pqe',
  'cjk' => 'bnt',
  'xwo' => 'xgn',
  'dur' => 'alv',
  'zgh' => 'ber',
  'nav' => 'apa',
  'mag' => 'inc',
  'arp' => 'alg',
  'erg' => 'pqe',
  'rmv' => 'art',
  'zty' => 'omq',
  'mxj' => 'tbq',
  'snx' => 'sem',
  'xmr' => 'ssa',
  'nwi' => 'pqe',
  'ozm' => 'alv',
  'tcy' => 'dra',
  'rif' => 'ber',
  'kdr' => 'trk',
  'unr' => 'mun',
  'aty' => 'pqe',
  'goq' => 'pqw',
  'thv' => 'ber',
  'nbl' => 'bnt',
  'quv' => 'myn',
  'tuk' => 'trk',
  'upv' => 'pqe',
  'bng' => 'bnt',
  'ikx' => 'ssa',
  'xgl' => 'bat',
  'tnr' => 'alv',
  'afa' => 'mul',
  'mqu' => 'sdv',
  'mog' => 'phi',
  'ary' => 'sem',
  'ilo' => 'phi',
  'ybe' => 'trk',
  'afr' => 'gmw',
  'kmj' => 'dra',
  'nij' => 'pqw',
  'frt' => 'pqe',
  'xum' => 'itc',
  'swb' => 'bnt',
  'grb' => 'kro',
  'rmt' => 'inc',
  'pgk' => 'pqe',
  'mug' => 'cdc',
  'ler' => 'pqe',
  'xeb' => 'sem',
  'sei' => 'hok',
  'kie' => 'ssa',
  'fao' => 'gmq',
  'knu' => 'dmn',
  'lmu' => 'pqe',
  'gos' => 'gmw',
  'mdr' => 'pqw',
  'mwl' => 'roa',
  'mey' => 'sem',
  'xpu' => 'sem',
  'kur' => 'ira',
  'klj' => 'trk',
  'nku' => 'alv',
  'mse' => 'cdc',
  'pdc' => 'gmw',
  'mqm' => 'pqe',
  'biq' => 'pqe',
  'kxu' => 'dra',
  'abl' => 'pqw',
  'cdd' => 'mul',
  'jkr' => 'sit',
  'uli' => 'pqe',
  'tli' => 'xnd',
  'wbp' => 'aus',
  'gyr' => 'tup',
  'ajt' => 'sem',
  'aar' => 'cus',
  'kws' => 'bnt',
  'koy' => 'ath',
  'sga' => 'cel',
  'bnr' => 'pqe',
  'dhv' => 'pqe',
  'nio' => 'syd',
  'yuy' => 'xgn',
  'nog' => 'tut',
  'esx' => 'mul',
  'pmz' => 'omq',
  'hok' => 'mul',
  'dun' => 'pqw',
  'mee' => 'pqe',
  'tsn' => 'bnt',
  'moa' => 'dmn',
  'beh' => 'alv',
  'dup' => 'pqw',
  'etn' => 'pqe',
  'gdq' => 'sem',
  'ckv' => 'fox',
  'tam' => 'dra',
  'ixl' => 'myn',
  'anz' => 'paa',
  'bez' => 'bnt',
  'iow' => 'xsi',
  'trk' => 'tut',
  'guh' => 'awd',
  'pqe' => 'poz',
  'izh' => 'fiu',
  'kas' => 'inc',
  'irk' => 'cus',
  'ero' => 'sit',
  'jya' => 'tbq',
  'lom' => 'dmn',
  'kay' => 'tup',
  'rsl' => 'sgn',
  'xbm' => 'cel',
  'sbb' => 'pqe',
  'ibo' => 'alv',
  'cpp' => 'roa',
  'ddj' => 'aus',
  'ojs' => 'alg',
  'esq' => 'hok',
  'obi' => 'hok',
  'xwe' => 'alv',
  'zho' => 'zhx',
  'csb' => 'zlw',
  'eve' => 'tuw',
  'crs' => 'cpf',
  'bid' => 'cdc',
  'ldn' => 'art',
  'ath' => 'xnd',
  'yii' => 'aus',
  'stq' => 'gmw',
  'pse' => 'pqw',
  'bce' => 'alv',
  'txb' => 'ine',
  'mwm' => 'csu',
  'igs' => 'art',
  'sem' => 'afa',
  'ldm' => 'alv',
  'dyo' => 'alv',
  'crv' => 'mkh',
  'sbh' => 'pqe',
  'ota' => 'trk',
  'kqn' => 'bnt',
  'btz' => 'btk',
  'arz' => 'sem',
  'mrc' => 'hok',
  'agw' => 'pqe',
  'dal' => 'cus',
  'piz' => 'pqe',
  'doz' => 'omv',
  'ani' => 'ccn',
  'abq' => 'ccn',
  'lkt' => 'xsi',
  'lrz' => 'pqe',
  'sma' => 'smi',
  'evn' => 'tuw',
  'ctu' => 'myn',
  'caq' => 'mkh',
  'srm' => 'cpp',
  'lbe' => 'ccn',
  'mnv' => 'pqe',
  'sov' => 'pqe',
  'tae' => 'awd',
  'oac' => 'tuw',
  'sco' => 'gmw',
  'akr' => 'pqe',
  'chr' => 'iro',
  'pus' => 'ira',
  'jdt' => 'ira',
  'mhy' => 'pqw',
  'lga' => 'pqe',
  'xpc' => 'trk',
  'krl' => 'fiu',
  'shh' => 'azc',
  'bsc' => 'alv',
  'pip' => 'cdc',
  'xkq' => 'pqw',
  'aiw' => 'omv',
  'srq' => 'tup',
  'wxa' => 'zhx',
  'vai' => 'dmn',
  'wow' => 'pqw',
  'urv' => 'pqe',
  'nwb' => 'kro',
  'kqr' => 'pqw',
  'ndo' => 'bnt',
  'bad' => 'alv',
  'otr' => 'alv',
  'xld' => 'ine',
  'wic' => 'cdd',
  'kru' => 'dra',
  'ktm' => 'pqe',
  'tur' => 'trk',
  'ddd' => 'sdv',
  'sun' => 'pqw',
  'gei' => 'pqe',
  'kss' => 'alv',
  'yal' => 'dmn',
  'swx' => 'auf',
  'nmy' => 'sit',
  'jae' => 'pqe',
  'dez' => 'bnt',
  'wiy' => 'aql',
  'yrl' => 'tup',
  'nkr' => 'pqe',
  'ttt' => 'ira',
  'lbb' => 'pqe',
  'hts' => 'khi',
  'rml' => 'inc',
  'niu' => 'pqe',
  'pbo' => 'alv',
  'azo' => 'alv',
  'brx' => 'tbq',
  'bea' => 'ath',
  'cjh' => 'sal',
  'win' => 'xsi',
  'bzd' => 'cba',
  'tbq' => 'sit',
  'rka' => 'mkh',
  'hei' => 'wak',
  'nfl' => 'pqe',
  'noc' => 'wak',
  'aac' => 'cdd',
  'huo' => 'mkh',
  'dag' => 'alv',
  'gsw' => 'gmw',
  'ltg' => 'bat',
  'mrj' => 'fiu',
  'dje' => 'son',
  'umb' => 'bnt',
  'mjg' => 'xgn',
  'liw' => 'sal',
  'mpz' => 'cdc',
  'mtq' => 'mkh',
  'slz' => 'pqe',
  'bwt' => 'bnt',
  'pot' => 'alg',
  'gly' => 'ssa',
  'bba' => 'alv',
  'mas' => 'sdv',
  'pkg' => 'pqe',
  'tll' => 'bnt',
  'sgn' => 'mul',
  'ndf' => 'bat',
  'yee' => 'paa',
  'iba' => 'pqw',
  'rog' => 'cmc',
  'twt' => 'tup',
  'onw' => 'nub',
  'sac' => 'alg',
  'raz' => 'pqw',
  'mlq' => 'dmn',
  'asz' => 'pqe',
  'mot' => 'cba',
  'kek' => 'myn',
  'ulu' => 'pqw',
  'kdt' => 'aav',
  'khm' => 'mkh',
  'yap' => 'pqe',
  'sba' => 'csu',
  'kha' => 'mkh',
  'kpe' => 'dmn',
  'mpu' => 'tup',
  'gzn' => 'pqe',
  'mwc' => 'pqe',
  'peh' => 'xgn',
  'tjg' => 'pqw',
  'hmd' => 'hmx',
  'fla' => 'sal',
  'fsl' => 'sgn',
  'bck' => 'aus',
  'sad' => 'khi',
  'mzq' => 'pqw',
  'mzw' => 'alv',
  'lat' => 'itc',
  'cjs' => 'trk',
  'aze' => 'trk',
  'pag' => 'phi',
  'niq' => 'sdv',
  'tpr' => 'tup',
  'ada' => 'alv',
  'xnt' => 'alg',
  'rmg' => 'gmq',
  'apu' => 'awd',
  'guk' => 'ssa',
  'uve' => 'pqe',
  'prk' => 'mkh',
  'cat' => 'roa',
  'nnz' => 'bai',
  'iru' => 'dra',
  'bzg' => 'fox',
  'goh' => 'gmw',
  'tnw' => 'phi',
  'sva' => 'ccs',
  'phl' => 'inc',
  'thp' => 'sal',
  'gla' => 'cel',
  'hat' => 'cpf',
  'roh' => 'roa',
  'bik' => 'phi',
  'moe' => 'alg',
  'eme' => 'tup',
  'teu' => 'ssa',
  'mun' => 'aav',
  'scb' => 'mkh',
  'fox' => 'map',
  'alz' => 'sdv',
  'kdh' => 'alv',
  'mmx' => 'pqe',
  'sob' => 'pqe',
  'ysr' => 'esx',
  'ubr' => 'pqe',
  'kbp' => 'alv',
  'tqu' => 'paa',
  'apj' => 'apa',
  'gdo' => 'ccn',
  'vmg' => 'pqe',
  'uzb' => 'trk',
  'arg' => 'roa',
  'ray' => 'pqe',
  'zen' => 'ber',
  'bnt' => 'alv',
  'nmb' => 'pqe',
  'sus' => 'dmn',
  'hrw' => 'pqe',
  'tyv' => 'trk',
  'rai' => 'pqe',
  'che' => 'ccn',
  'vra' => 'pqe',
  'ruk' => 'ccn',
  'tlb' => 'paa',
  'srp' => 'zls',
  'paa' => 'mul',
  'tac' => 'azc',
  'ggt' => 'pqe',
  'mzn' => 'ira',
  'pku' => 'pqw',
  'mov' => 'hok',
  'lfn' => 'art',
  'mnw' => 'xgn',
  'saj' => 'paa',
  'mmw' => 'pqe',
  'pon' => 'pqe',
  'xce' => 'cel',
  'soy' => 'alv',
  'neg' => 'tuw',
  'kkj' => 'bnt',
  'vol' => 'art',
  'yaq' => 'azc',
  'bju' => 'alv',
  'hau' => 'cdc',
  'lgk' => 'pqe',
  'mhj' => 'xgn',
  'bvc' => 'pqe',
  'trp' => 'tbq',
  'nqn' => 'pqe',
  'yky' => 'alv',
  'mde' => 'ssa',
  'ify' => 'phi',
  'irh' => 'pqe',
  'nyl' => 'aav',
  'sdg' => 'inc',
  'snl' => 'phi',
  'hmx' => 'mul',
  'pdo' => 'pqw',
  'abs' => 'pqw',
  'xbp' => 'aus',
  'zng' => 'mkh',
  'bam' => 'dmn',
  'run' => 'bnt',
  'pkn' => 'aus',
  'sns' => 'pqe',
  'xpq' => 'alg',
  'pcd' => 'roa',
  'sxr' => 'fox',
  'mkv' => 'pqe',
  'map' => 'mul',
  'din' => 'sdv',
  'sid' => 'cus',
  'bae' => 'awd',
  'kys' => 'pqw',
  'mxe' => 'pqe',
  'apa' => 'ath',
  'fry' => 'gmw',
  'neu' => 'art',
  'kkz' => 'ath',
  'gml' => 'gmw',
  'prg' => 'bat',
  'naq' => 'khi',
  'alc' => 'aqa',
  'knk' => 'dmn',
  'kxv' => 'dra',
  'aql' => 'mul',
  'dbl' => 'aus',
  'acf' => 'cpf',
  'lol' => 'bnt',
  'kff' => 'dra',
  'nzi' => 'alv',
  'syr' => 'sem',
  'knj' => 'myn',
  'peo' => 'ira',
  'cbn' => 'mkh',
  'unm' => 'alg',
  'ems' => 'ypk',
  'sln' => 'hok',
  'sas' => 'pqw',
  'nnn' => 'cdc',
  'bdh' => 'csu',
  'ple' => 'poz',
  'tcx' => 'dra',
  'pma' => 'pqe',
  'swe' => 'gmq',
  'kvh' => 'poz',
  'bqj' => 'alv',
  'kho' => 'ira',
  'kno' => 'dmn',
  'blr' => 'mkh',
  'fap' => 'alv',
  'agx' => 'ccn',
  'afh' => 'art',
  'bvb' => 'bnt',
  'cow' => 'sal',
  'pil' => 'alv',
  'akv' => 'ccn',
  'kgk' => 'tup',
  'njo' => 'tbq',
  'lml' => 'pqe',
  'xlg' => 'ine',
  'cri' => 'cpp',
  'lpo' => 'tbq',
  'khw' => 'inc',
  'tlv' => 'plf',
  'brg' => 'awd',
  'tui' => 'alv',
  'llf' => 'pqe',
  'gld' => 'tuw',
  'ing' => 'ath',
  'bla' => 'alg',
  'xbr' => 'poz',
  'vrt' => 'pqe',
  'aol' => 'poz',
  'kdo' => 'nic',
  'hsb' => 'wen',
  'nun' => 'tbq',
  'bas' => 'bnt',
  'mkj' => 'pqe',
  'brh' => 'dra',
  'fon' => 'alv',
  'lzz' => 'ccs',
  'mnh' => 'alv',
  'efi' => 'alv',
  'end' => 'poz',
  'mns' => 'fiu',
  'nnt' => 'alg',
  'bhp' => 'poz',
  'osc' => 'itc',
  'omq' => 'mul',
  'hid' => 'xsi',
  'gme' => 'gem',
  'rro' => 'pqe',
  'kdx' => 'bnt',
  'shr' => 'bnt',
  'nwc' => 'sit',
  'dgg' => 'pqe',
  'nub' => 'sdv',
  'mdx' => 'omv',
  'byn' => 'cus',
  'pme' => 'pqe',
  'cjm' => 'cmc',
  'rap' => 'pqe',
  'mrv' => 'pqe',
  'skr' => 'inc',
  'asa' => 'bnt',
  'cad' => 'cdd',
  'gob' => 'awd',
  'wru' => 'pqw',
  'aoa' => 'cpp',
  'xmk' => 'ine',
  'bkh' => 'bnt',
  'chp' => 'ath',
  'duw' => 'pqw',
  'aib' => 'trk',
  'txg' => 'sit',
  'mdi' => 'csu',
  'shx' => 'omv',
  'mkm' => 'pqw',
  'irr' => 'aav',
  'gle' => 'cel',
  'buk' => 'pqe',
  'ckb' => 'ira',
  'kzr' => 'alv',
  'lle' => 'pqe',
  'zhx' => 'sit',
  'tgc' => 'pqe',
  'npn' => 'pqe',
  'btx' => 'btk',
  'sht' => 'hok',
  'kab' => 'ber',
  'xlb' => 'alg',
  'tbz' => 'alv',
  'bnq' => 'phi',
  'bmv' => 'bnt',
  'lhu' => 'tbq',
  'wmt' => 'aus',
  'zbe' => 'pqw',
  'scx' => 'ine',
  'adj' => 'alv',
  'ksh' => 'gmw',
  'pop' => 'pqe',
  'vot' => 'fiu',
  'rou' => 'ssa',
  'tuq' => 'ssa',
  'sne' => 'dai',
  'fos' => 'fox',
  'mrm' => 'pqe',
  'mgo' => 'alv',
  'cup' => 'azc',
  'sna' => 'bnt',
  'czk' => 'zlw',
  'xto' => 'ine',
  'fij' => 'pqe',
  'xpg' => 'ine',
  'mez' => 'alg',
  'eto' => 'bnt',
  'zbw' => 'pqw',
  'her' => 'bnt',
  'frm' => 'roa',
  'tau' => 'ath',
  'mam' => 'myn',
  'dta' => 'xgn',
  'bjn' => 'pqw',
  'sbp' => 'bnt',
  'ski' => 'poz',
  'jgo' => 'bai',
  'zlw' => 'sla',
  'nba' => 'bnt',
  'lee' => 'alv',
  'xfa' => 'itc',
  'ofs' => 'gmw',
  'blo' => 'alv',
  'dma' => 'bnt',
  'poh' => 'myn',
  'hye' => 'ine',
  'lgn' => 'ssa',
  'bja' => 'bnt',
  'iku' => 'esx',
  'hni' => 'sit',
  'uun' => 'fox',
  'mvf' => 'xgn',
  'ira' => 'iir',
  'nmn' => 'khi',
  'tay' => 'fox',
  'amv' => 'plf',
  'bbl' => 'ccn',
  'pqw' => 'poz',
  'bsu' => 'pqw',
  'sjt' => 'smi',
  'xgf' => 'azc',
  'tox' => 'pqe',
  'drg' => 'pqw',
  'nrn' => 'gmq',
  'cre' => 'alg',
  'ind' => 'pqw',
  'lub' => 'bnt',
  'dzg' => 'ssa',
  'crc' => 'pqe',
  'phn' => 'sem',
  'eus' => 'euq',
  'kea' => 'cpp',
  'gmb' => 'pqe',
  'bew' => 'pqw',
  'sxg' => 'sit',
  'osx' => 'gmw',
  'uvl' => 'pqe',
  'snf' => 'alv',
  'kal' => 'esx',
  'kjb' => 'myn',
  'xaa' => 'sem',
  'ivv' => 'poz',
  'nov' => 'art',
  'zim' => 'cdc',
  'smw' => 'pqw',
  'khq' => 'son',
  'mwh' => 'pqe',
  'mbp' => 'cba',
  'rri' => 'pqe',
  'kpg' => 'pqe',
  'fil' => 'phi',
  'ssa' => 'mul',
  'bjk' => 'pqe',
  'tuv' => 'sdv',
  'bcq' => 'omv',
  'son' => 'ssa',
  'sss' => 'aav',
  'krj' => 'phi',
  'bsq' => 'kro',
  'ndv' => 'alv',
  'div' => 'inc',
  'ext' => 'roa',
  'zdj' => 'bnt',
  'xmw' => 'pqw',
  'wlm' => 'cel',
  'amh' => 'sem',
  'xnb' => 'fox',
  'dzo' => 'sit',
  'cjy' => 'zhx',
  'ess' => 'ypk',
  'xsy' => 'fox',
  'kdj' => 'sdv',
  'tel' => 'dra',
  'nrf' => 'roa',
  'pex' => 'pqe',
  'eka' => 'nic',
  'mxi' => 'roa',
  'com' => 'azc',
  'bfd' => 'alv',
  'myb' => 'csu',
  'mno' => 'phi',
  'ijo' => 'alv',
  'sda' => 'pqw',
  'fia' => 'nub',
  'krc' => 'trk',
  'tkg' => 'pqw',
  'kbl' => 'ssa',
  'abi' => 'alv',
  'bda' => 'alv',
  'zle' => 'sla',
  'otw' => 'alg',
  'dgr' => 'ath',
  'toi' => 'bnt',
  'duu' => 'tbq',
  'sxl' => 'bat',
  'rad' => 'cmc',
  'tlm' => 'pqe',
  'por' => 'roa',
  'lcm' => 'pqe',
  'tnn' => 'pqe',
  'cwg' => 'mkh',
  'sjm' => 'pqw',
  'anx' => 'pqe',
  'tmc' => 'cdc',
  'uig' => 'trk',
  'frr' => 'gmw',
  'sbe' => 'pqe',
  'hrv' => 'zls',
  'sdv' => 'ssa',
  'kde' => 'bnt',
  'kbm' => 'pqe',
  'yij' => 'aus',
  'tpx' => 'omq',
  'zaw' => 'omq',
  'lch' => 'bnt',
  'yur' => 'aql',
  'tum' => 'bnt',
  'ora' => 'pqe',
  'ksd' => 'pqe',
  'fas' => 'ira',
  'tuw' => 'tut',
  'mfv' => 'alv',
  'mqy' => 'poz',
  'kom' => 'fiu',
  'pef' => 'hok',
  'mfy' => 'azc',
  'goy' => 'alv',
  'ori' => 'inc',
  'wbl' => 'ira',
  'hla' => 'pqe',
  'bko' => 'bai',
  'gmq' => 'gem',
  'dra' => 'mul',
  'grz' => 'pqe',
  'zbl' => 'art',
  'ady' => 'ccn',
  'prn' => 'iir',
  'man' => 'dmn',
  'tat' => 'trk',
  'dim' => 'omv',
  'aru' => 'auf',
  'bwn' => 'hmx',
  'kwz' => 'khi',
  'kog' => 'cba',
  'isg' => 'sgn',
  'bje' => 'hmx',
  'art' => 'mul',
  'hop' => 'azc',
  'ghn' => 'pqe',
  'siz' => 'ber',
  'spx' => 'itc',
  'hke' => 'bnt',
  'tlx' => 'pqe',
  'tdi' => 'pqw',
  'ngr' => 'pqe',
  'stw' => 'pqe',
  'nsw' => 'pqe',
  'lgr' => 'pqe',
  'nym' => 'bnt',
  'naj' => 'alv',
  'avi' => 'alv',
  'ong' => 'fiu',
  'yuf' => 'hok',
  'klb' => 'hok',
  'mah' => 'pqe',
  'dmn' => 'nic',
  'bpy' => 'inc',
  'bci' => 'alv',
  'seh' => 'bnt',
  'bno' => 'phi',
  'rug' => 'pqe',
  'lun' => 'bnt',
  'kju' => 'hok',
  'uzs' => 'trk',
  'kum' => 'trk',
  'bot' => 'csu',
  'lue' => 'bnt',
  'abx' => 'pqw',
  'lpx' => 'sdv',
  'tzo' => 'myn',
  'frk' => 'gmw',
  'tif' => 'paa',
  'mgl' => 'pqe',
  'bat' => 'ine',
  'ibg' => 'phi',
  'hoi' => 'xnd',
  'bth' => 'dai',
  'duq' => 'pqw',
  'kry' => 'ccn',
  'bbc' => 'btk',
  'gej' => 'alv',
  'lyn' => 'bnt',
  'bdg' => 'pqw',
  'sya' => 'pqw',
  'bqc' => 'dmn',
  'pnu' => 'hmx',
  'gqr' => 'phi',
  'mar' => 'inc',
  'sjr' => 'pqe',
  'pnt' => 'grk',
  'uga' => 'sem',
  'xzm' => 'bat',
  'xcl' => 'ine',
  'maj' => 'omq',
  'bcr' => 'ath',
  'lmo' => 'roa',
  'xmv' => 'pqw',
  'acw' => 'sem',
  'wha' => 'plf',
  'cqd' => 'hmx',
  'bgj' => 'alv',
  'kir' => 'trk',
  'cui' => 'awd',
  'mak' => 'pqw',
  'ang' => 'gmw',
  'auf' => 'mul',
  'jic' => 'ath',
  'see' => 'iro',
  'tzh' => 'myn',
  'gmy' => 'grk',
  'shy' => 'ber',
  'str' => 'sal',
  'bkw' => 'bnt',
  'nau' => 'pqe',
  'tbe' => 'pqe',
  'mpr' => 'pqe',
  'mzb' => 'ber',
  'cop' => 'afa',
  'mad' => 'pqw',
  'hed' => 'cdc',
  'xsv' => 'bat',
  'cam' => 'pqe',
  'ast' => 'roa',
  'jhi' => 'mkh',
  'nsg' => 'sdv',
  'srs' => 'ath',
  'bul' => 'zls',
  'inc' => 'iir',
  'yrk' => 'syd',
  'wiv' => 'pqe',
  'krf' => 'pqe',
  'ndp' => 'bnt',
  'znd' => 'nic',
  'pgu' => 'paa',
  'los' => 'pqe',
  'vkl' => 'pqw',
  'fin' => 'fiu',
  'khv' => 'ccn',
  'dic' => 'kro',
  'lbv' => 'pqe',
  'boi' => 'hok',
  'mdj' => 'csu',
  'shs' => 'sal',
  'nsn' => 'pqe',
  'bji' => 'cus',
  'mor' => 'alv',
  'enm' => 'gmw',
  'fip' => 'bnt',
  'men' => 'dmn',
  'sit' => 'mul',
  'xps' => 'ine',
  'smn' => 'smi',
  'awa' => 'inc',
  'coc' => 'hok',
  'ssw' => 'bnt',
  'new' => 'sit',
  'kqs' => 'alv',
  'sml' => 'pqw',
  'frc' => 'roa',
  'bni' => 'bnt',
  'bjz' => 'ngf',
  'got' => 'gme',
  'ccc' => 'awd',
  'mrn' => 'pqe',
  'fwa' => 'pqe',
  'pss' => 'pqe',
  'kua' => 'bnt',
  'bai' => 'alv',
  'brr' => 'pqe',
  'ppn' => 'pqe',
  'caf' => 'ath',
  'jrb' => 'sem',
  'sot' => 'bnt',
  'hoa' => 'pqe',
  'oku' => 'alv',
  'bdr' => 'pqw',
  'xsi' => 'pqe',
  'tec' => 'sdv',
  'llx' => 'pqe',
  'wal' => 'omv',
  'aii' => 'sem',
  'zls' => 'sla',
  'gur' => 'alv',
  'tlr' => 'pqe',
  'cak' => 'myn',
  'saq' => 'sdv',
  'sat' => 'mun',
  'rej' => 'pqw',
  'txs' => 'phi',
  'nmt' => 'pqe',
  'bra' => 'inc',
  'keu' => 'alv',
  'cro' => 'xsi',
  'abk' => 'ccn',
  'bsg' => 'ira',
  'vwa' => 'mkh',
  'jac' => 'myn',
  'tbf' => 'pqe',
  'qyp' => 'alg',
  'ane' => 'pqe',
  'heb' => 'sem',
  'cco' => 'omq',
  'bel' => 'zle',
  'mwr' => 'inc',
  'sgl' => 'ira',
  'lww' => 'pqe',
  'nuy' => 'aus',
  'one' => 'iro',
  'oaa' => 'tuw',
  'kin' => 'bnt',
  'uge' => 'pqe',
  'xsd' => 'ine',
  'lik' => 'bnt',
  'fax' => 'roa',
  'tmh' => 'ber',
  'pek' => 'pqe',
  'rar' => 'pqe',
  'tcm' => 'paa',
  'lid' => 'pqe',
  'mnr' => 'azc',
  'mal' => 'dra',
  'mxb' => 'omq',
  'ach' => 'sdv',
  'mdd' => 'alv',
  'smj' => 'smi',
  'afb' => 'sem',
  'tus' => 'iro',
  'yai' => 'ira',
  'acv' => 'hok',
  'kjj' => 'ccn',
  'grr' => 'ber',
  'tha' => 'taw',
  'bcu' => 'pqe',
  'xcu' => 'bat',
  'nxq' => 'sit',
  'auh' => 'bnt',
  'txh' => 'ine',
  'dor' => 'pqe',
  'shu' => 'sem',
  'nha' => 'aus',
  'lav' => 'bat',
  'tnk' => 'pqe',
  'tgi' => 'pqe',
  'sol' => 'pqe',
  'aht' => 'ath',
  'mxr' => 'pqw',
  'nic' => 'mul',
  'inh' => 'ccn',
  'kqw' => 'pqe',
  'kge' => 'pqw',
  'grc' => 'grk',
  'nnb' => 'bnt',
  'cdo' => 'zhx',
  'mgh' => 'bnt',
  'goo' => 'pqe',
  'atk' => 'alv',
  'heh' => 'bnt',
  'hoo' => 'bnt',
  'sgd' => 'phi',
  'tik' => 'alv',
  'plf' => 'poz',
  'njm' => 'sit',
  'trv' => 'fox',
  'pib' => 'awd',
  'tpw' => 'tup',
  'wya' => 'iro',
  'tla' => 'azc',
  'mtt' => 'pqe',
  'sog' => 'ira',
  'mbn' => 'awd',
  'bcm' => 'pqe',
  'zgr' => 'pqe',
  'snq' => 'bnt',
  'pic' => 'bnt',
  'urj' => 'mul',
  'kik' => 'bnt',
  'dij' => 'pqw',
  'nmg' => 'bnt',
  'jbn' => 'ber',
  'nds' => 'gmw',
  'ixc' => 'omq',
  'mmt' => 'pqe',
  'ask' => 'iir',
  'nah' => 'azc',
  'orc' => 'cus',
  'lmg' => 'pqe',
  'bkc' => 'alv',
  'kwk' => 'wak',
  'gem' => 'ine',
  'crd' => 'sal',
  'nxm' => 'ber',
  'sps' => 'pqe',
  'opt' => 'azc',
  'xga' => 'cel',
  'kls' => 'inc',
  'cmc' => 'pqw',
  'cul' => 'auf',
  'twy' => 'pqw',
  'zap' => 'omq',
  'nqo' => 'nic',
  'cbg' => 'cba',
  'mrl' => 'pqe',
  'wbk' => 'iir',
  'myv' => 'fiu',
  'llu' => 'pqe',
  'hch' => 'azc',
  'eno' => 'pqw',
  'smo' => 'pqe',
  'huz' => 'ccn',
  'tmy' => 'pqe',
  'kmo' => 'paa',
  'ngf' => 'paa',
  'vmb' => 'aus',
  'fcs' => 'sgn',
  'vnm' => 'pqe',
  'tab' => 'ccn',
  'mlv' => 'pqe',
  'utp' => 'pqe',
  'oyb' => 'mkh',
  'vko' => 'pqw',
  'bns' => 'inc',
  'var' => 'azc',
  'ynk' => 'ypk',
  'toq' => 'sdv',
  'acy' => 'sem',
  'wep' => 'gmw',
  'non' => 'gmq',
  'pio' => 'awd',
  'atw' => 'hok',
  'pnh' => 'pqe',
  'nus' => 'sdv',
  'kon' => 'bnt',
  'ssy' => 'cus',
  'bhw' => 'pqe',
  'ave' => 'ira',
  'guz' => 'bnt',
  'pol' => 'zlw',
  'beg' => 'pqw',
  'dav' => 'bnt',
  'hmr' => 'sit',
  'blp' => 'pqe',
  'hao' => 'pqe',
  'mmy' => 'cdc',
  'fqs' => 'ira',
  'wym' => 'gmw',
  'guo' => 'awd',
  'mfa' => 'pqw',
  'aba' => 'alv',
  'msa' => 'sal',
  'cps' => 'phi',
  'ebr' => 'alv',
  'ina' => 'art',
  'ptp' => 'pqe',
  'arq' => 'sem',
  'ceb' => 'phi',
  'tpv' => 'pqe',
  'kar' => 'sit',
  'xgn' => 'tut',
  'qvy' => 'sit',
  'som' => 'cus',
  'ewo' => 'bnt',
  'tzj' => 'myn',
  'mri' => 'pqe',
  'xcb' => 'cel',
  'mfe' => 'cpf',
  'aqa' => 'mul',
  'aut' => 'pqe',
  'wwa' => 'alv',
  'tfn' => 'xnd',
  'bxf' => 'pqe',
  'scl' => 'inc',
  'kkk' => 'pqe',
  'spp' => 'alv',
  'piv' => 'pqe',
  'tdn' => 'phi',
  'mla' => 'pqe',
  'pfl' => 'gmw',
  'tkw' => 'pqe',
  'bts' => 'btk',
  'koq' => 'bnt',
  'iii' => 'sit',
  'sjn' => 'art',
  'bpn' => 'hmx',
  'nde' => 'bnt',
  'nfr' => 'alv',
  'nob' => 'gmq',
  'yor' => 'alv',
  'nep' => 'inc',
  'kro' => 'alv',
  'clc' => 'ath',
  'czh' => 'zhx',
  'lgb' => 'pqe',
  'zne' => 'znd',
  'dny' => 'auf',
  'puy' => 'hok',
  'gmh' => 'gmw',
  'mmr' => 'hmx',
  'min' => 'pqw',
  'tut' => 'mul',
  'jpn' => 'jpx',
  'luy' => 'bnt',
  'syc' => 'sem',
  'nal' => 'pqe',
  'far' => 'pqe',
  'nnd' => 'pqe',
  'bfa' => 'sdv',
  'xao' => 'mkh',
  'sqn' => 'iro',
  'roa' => 'itc',
  'nnc' => 'cdc',
  'wuv' => 'pqe',
  'kic' => 'alg',
  'swa' => 'swa',
  'ojw' => 'alg',
  'tiv' => 'alv',
  'mhb' => 'bnt',
  'cid' => 'hok',
  'bll' => 'xsi',
  'aus' => 'mul',
  'dtr' => 'pqw',
  'led' => 'csu',
  'tmi' => 'pqe',
  'tlh' => 'art',
  'bkz' => 'pqw',
  'kuu' => 'ath',
  'chy' => 'alg',
  'jnj' => 'omv',
  'clw' => 'trk',
  'taq' => 'ber',
  'sgh' => 'ira',
  'ssf' => 'fox',
  'kaa' => 'trk',
  'bjj' => 'inc',
  'tgk' => 'ira',
  'tly' => 'ira',
  'tgs' => 'pqe',
  'mhi' => 'csu',
  'msb' => 'phi',
  'tso' => 'bnt',
  'soh' => 'alv',
  'stn' => 'pqe',
  'gwc' => 'inc',
  'poz' => 'map',
  'mtd' => 'pqw',
  'smp' => 'sem',
  'jbo' => 'art',
  'kei' => 'poz',
  'wci' => 'alv',
  'kok' => 'inc',
  'xve' => 'ine',
  'kmv' => 'cpf',
  'peb' => 'hok',
  'bip' => 'bnt',
  'gay' => 'pqw',
  'stp' => 'azc',
  'nas' => 'paa',
  'kyj' => 'phi',
  'rng' => 'bnt',
  'rth' => 'phi',
  'cae' => 'alv',
  'cms' => 'ine',
  'lht' => 'pqe',
  'mlf' => 'mkh',
  'xcr' => 'ine',
  'asm' => 'inc',
  'ekg' => 'ngf',
  'mqn' => 'pqw',
  'tzm' => 'ber',
  'maq' => 'omq',
  'kjc' => 'pqw',
  'aau' => 'paa',
  'odt' => 'gmw',
  'mwk' => 'dmn',
  'gan' => 'zhx',
  'ton' => 'pqe',
  'tnp' => 'pqe',
  'pad' => 'auf',
  'nms' => 'pqe',
  'xrg' => 'aus',
  'sse' => 'pqw',
  'myh' => 'wak',
  'lti' => 'plf',
  'gwi' => 'ath',
  'nrm' => 'pqw',
  'gba' => 'alv',
  'anp' => 'ine',
  'kwf' => 'pqe',
  'rue' => 'zle',
  'kpc' => 'awd',
  'nia' => 'pqw',
  'mnu' => 'bnt',
  'xsc' => 'ira',
  'ply' => 'mkh',
  'qun' => 'sal',
  'ayl' => 'sem',
  'xal' => 'xgn',
  'sku' => 'pqe',
  'gxx' => 'kro',
  'oma' => 'xsi',
  'ksk' => 'xsi',
  'mos' => 'alv',
  'srh' => 'ira',
  'glg' => 'roa',
  'syd' => 'urj',
  'tuc' => 'pqe',
  'mya' => 'sit',
  'bzt' => 'art',
  'kck' => 'bnt',
  'pmt' => 'pqe',
  'nmk' => 'pqe',
  'tcb' => 'ath',
  'urr' => 'pqe',
  'wuu' => 'zhx',
  'ynn' => 'hok',
  'smi' => 'fiu',
  'ahb' => 'pqe',
  'tar' => 'azc',
  'cks' => 'cpf',
  'gin' => 'ccn',
  'emx' => 'inc',
  'pov' => 'cpp',
  'kpz' => 'sdv',
  'gct' => 'gmw',
  'ksb' => 'bnt',
  'luo' => 'sdv',
  'guq' => 'tup',
  'tmr' => 'sem',
  'kdk' => 'pqe',
  'psm' => 'tup',
  'mzv' => 'alv',
  'cau' => 'mul',
  'mwv' => 'pqw',
  'wli' => 'paa',
  'bxa' => 'pqe',
  'aeb' => 'sem',
  'raj' => 'inc',
  'tvk' => 'pqe',
  'sev' => 'alv',
  'tgp' => 'pqe',
  'mia' => 'alg',
  'keo' => 'sdv',
  'bgk' => 'mkh',
  'mop' => 'myn',
  'mjy' => 'alg',
  'ulc' => 'tuw',
  'dak' => 'xsi',
  'jpx' => 'mul',
  'tnl' => 'pqe',
  'ald' => 'kro',
  'nno' => 'gmq',
  'ttu' => 'pqe',
  'twm' => 'tbq',
  'mwo' => 'pqe',
  'sij' => 'pqe',
  'tvl' => 'pqe',
  'pej' => 'hok',
  'alv' => 'nic',
  'cac' => 'myn',
  'ewe' => 'alv',
  'chl' => 'azc',
  'daa' => 'cdc',
  'tir' => 'sem',
  'bak' => 'trk',
  'eng' => 'gmw',
  'txn' => 'plf',
  'mlg' => 'pqw',
  'kpn' => 'tup',
  'bgt' => 'pqe',
  'bqz' => 'bnt',
  'qua' => 'xsi',
  'uby' => 'ccn',
  'fvr' => 'ssa',
  'siy' => 'ira',
  'kuv' => 'ira',
  'akl' => 'phi',
  'pox' => 'zlw',
  'huq' => 'cmc',
  'mcn' => 'cdc',
  'mlt' => 'sem',
  'mqt' => 'paa',
  'vec' => 'roa',
  'bzh' => 'pqe',
  'kln' => 'sdv',
  'kvc' => 'pqe',
  'vep' => 'fiu',
  'ctg' => 'inc',
  'buh' => 'hmx',
  'mqa' => 'pqe',
  'toj' => 'myn',
  'bsh' => 'iir',
  'bho' => 'inc',
  'war' => 'phi',
  'cay' => 'iro',
  'ine' => 'mul',
  'dyu' => 'dmn',
  'ttc' => 'myn',
  'mhn' => 'gmw',
  'fro' => 'roa',
  'muv' => 'dra',
  'ptv' => 'pqe',
  'pfa' => 'pqe',
  'teo' => 'sdv',
  'xsr' => 'sit',
  'agu' => 'myn',
  'zmw' => 'bnt',
  'cou' => 'alv',
  'kmb' => 'bnt',
  'erk' => 'pqe',
  'rwk' => 'bnt',
  'szw' => 'pqe',
  'dlm' => 'roa',
  'mfb' => 'pqw',
  'lme' => 'cdc',
  'udi' => 'ccn',
  'ara' => 'sem',
  'veo' => 'hok',
  'cwe' => 'bnt',
  'vun' => 'bnt',
  'est' => 'fiu',
  'aul' => 'pqe',
  'haz' => 'ira',
  'mga' => 'cel',
  'tpu' => 'mkh',
  'sce' => 'xgn',
  'mhc' => 'myn',
  'ofo' => 'xsi',
  'lus' => 'sit',
  'caa' => 'myn',
  'slr' => 'trk',
  'czn' => 'omq',
  'atj' => 'alg',
  'waj' => 'paa',
  'paw' => 'cdd',
  'xco' => 'ira',
  'cdc' => 'afa',
  'alt' => 'trk',
  'chb' => 'cba',
  'xvi' => 'iir',
  'kii' => 'cdd',
  'ruq' => 'roa',
  'bub' => 'xgn',
  'mji' => 'hmx',
  'fod' => 'alv',
  'kyh' => 'hok',
  'wyr' => 'tup',
  'bax' => 'alv',
  'chm' => 'fiu',
  'nga' => 'alv',
  'snk' => 'dmn',
  'tkr' => 'ccn',
  'bnk' => 'pqe',
  'avk' => 'art',
  'wni' => 'bnt',
  'ncf' => 'pqe',
  'rgn' => 'roa',
  'ddo' => 'ccn',
  'lrc' => 'ira',
  'anc' => 'cdc',
  'swc' => 'swa',
  'cos' => 'roa',
  'tsu' => 'fox',
  'tva' => 'pqe',
  'nyo' => 'nic',
  'zul' => 'bnt',
  'tom' => 'phi',
  'tyh' => 'mkh',
  'mua' => 'alv',
  'ayb' => 'alv',
  'myn' => 'mul',
  'gag' => 'trk',
  'kzk' => 'pqe',
  'bod' => 'tbq',
  'itz' => 'myn',
  'kcv' => 'bnt',
  'nhd' => 'tup',
  'kzu' => 'pqe',
  'lvk' => 'paa',
  'mhq' => 'xsi',
  'xnh' => 'mkh',
  'bem' => 'bnt',
  'kbd' => 'ccn',
  'skh' => 'pqw',
  'bdk' => 'ccn',
  'ava' => 'ccn',
  'iir' => 'ine',
  'pau' => 'pqw',
  'mbo' => 'bnt',
  'apw' => 'apa',
  'sme' => 'smi',
  'oto' => 'omq',
  'eya' => 'xnd',
  'gon' => 'dra',
  'ltc' => 'zhx',
  'njh' => 'sit',
  'itc' => 'ine',
  'lim' => 'gmw',
  'kfc' => 'dra',
  'kaw' => 'pqw',
  'lld' => 'roa',
  'pmn' => 'phi',
  'cal' => 'pqe',
  'kcy' => 'son',
  'hbu' => 'plf',
  'noz' => 'omv',
  'ssg' => 'pqe',
  'hit' => 'ine',
  'gap' => 'plf',
  'dan' => 'gmq',
  'oru' => 'ira',
  'ypk' => 'esx',
  'vif' => 'bnt',
  'kyk' => 'phi',
  'dlg' => 'trk',
  'tta' => 'xsi',
  'lij' => 'roa',
  'aua' => 'pqe',
  'kyi' => 'pqw',
  'mtm' => 'syd',
  'xdc' => 'ine',
  'dru' => 'fox',
  'rup' => 'roa',
  'oua' => 'ber',
  'mls' => 'ssa',
  'har' => 'sem',
  'kij' => 'pqe',
  'xxk' => 'poz',
  'cha' => 'pqw',
  'ybb' => 'bai',
  'squ' => 'sal',
  'tub' => 'azc',
  'loc' => 'phi',
  'arc' => 'sem',
  'pha' => 'hmx',
  'tqp' => 'pqe',
  'ktz' => 'khi',
  'wak' => 'mul',
  'tkp' => 'pqe',
  'yly' => 'pqe',
  'ttv' => 'pqe',
  'zza' => 'ira',
  'qwm' => 'trk',
  'aie' => 'pqe',
  'mui' => 'pqw',
  'wae' => 'gmw',
  'lsa' => 'ira',
  'yum' => 'hok',
  'moh' => 'iro',
  'arv' => 'cus',
  'ddg' => 'paa',
  'kje' => 'plf',
  'nke' => 'pqe',
  'not' => 'awd',
  'sgc' => 'sdv',
  'has' => 'wak',
  'ilk' => 'phi',
  'isk' => 'ira',
  'puw' => 'pqe',
  'nlg' => 'pqe',
  'sax' => 'pqe',
  'sla' => 'ine',
  'pim' => 'alg',
  'wbm' => 'mkh',
  'jra' => 'cmc',
  'mrw' => 'phi',
  'apl' => 'apa',
  'lng' => 'gmw',
  'sia' => 'smi',
  'mdh' => 'phi',
  'blf' => 'phi',
  'yao' => 'bnt',
  'gri' => 'pqe',
  'yua' => 'myn',
  'mep' => 'aus',
  'ful' => 'alv',
  'ale' => 'esx',
  'tig' => 'sem',
  'doi' => 'inc',
  'coo' => 'sal',
  'mai' => 'inc',
  'nxe' => 'poz',
  'rmq' => 'inc',
  'ppl' => 'azc',
  'zuy' => 'cdc',
  'faf' => 'pqe',
  'gux' => 'alv',
  'bkk' => 'inc',
  'aka' => 'alv',
  'lob' => 'alv',
  'czo' => 'zhx',
  'dar' => 'ccn',
  'nci' => 'nah',
  'grn' => 'tup',
  'mln' => 'pqe',
  'guc' => 'awd',
  'hlu' => 'ine',
  'sds' => 'ber',
  'fud' => 'pqe',
  'kva' => 'ccn',
  'hml' => 'hmx',
  'prc' => 'ira',
  'jab' => 'alv',
  'bdl' => 'pqw',
  'bug' => 'pqw',
  'xvn' => 'gme',
  'rus' => 'zle',
  'ood' => 'azc',
  'swg' => 'gmw',
  'pbp' => 'alv',
  'dua' => 'bnt',
  'hbs' => 'zls',
  'ntp' => 'azc',
  'cwt' => 'alv',
  'gqi' => 'tbq',
  'nor' => 'gmq',
  'lit' => 'bat',
  'gcr' => 'cpf',
  'ktq' => 'pqw',
  'lug' => 'bnt',
  'nza' => 'alv',
  'thy' => 'taw',
  'ses' => 'son',
  'slk' => 'zlw',
  'srd' => 'roa',
  'app' => 'pqe',
  'ntw' => 'iro',
  'ruo' => 'roa',
  'xmg' => 'bai',
  'meu' => 'pqe',
  'gga' => 'pqe',
  'sbc' => 'pqe',
  'haw' => 'pqe',
  'pre' => 'cpp',
  'mkd' => 'zls',
  'mvo' => 'pqe',
  'mjv' => 'dra',
  'kac' => 'sit',
  'ley' => 'pqw',
  'ber' => 'afa',
  'cje' => 'cmc',
  'ukr' => 'zle',
  'kjn' => 'aus',
  'ccn' => 'cau',
  'ron' => 'roa',
  'uuu' => 'mkh',
  'kxr' => 'pqe',
  'nld' => 'gmw',
  'fan' => 'bnt',
  'mhw' => 'bnt',
  'hah' => 'pqe',
  'hne' => 'inc',
  'lad' => 'roa',
  'azb' => 'trk',
  'wam' => 'alg',
  'mlo' => 'alv',
  'osp' => 'roa',
  'bxg' => 'bnt',
  'zea' => 'gmw',
  'apc' => 'sem',
  'myk' => 'alv',
  'lao' => 'taw',
  'xls' => 'ine',
  'oji' => 'alg',
  'rak' => 'pqe',
  'nla' => 'bai',
  'swp' => 'pqe',
  'nya' => 'bnt',
  'bvd' => 'pqe',
  'dsb' => 'wen',
  'ace' => 'cmc',
  'xho' => 'bnt',
  'ons' => 'iro',
  'gcf' => 'cpf',
  'sav' => 'alv',
  'sje' => 'smi',
  'aav' => 'mul',
  'kjh' => 'trk',
  'hun' => 'fiu',
  'haq' => 'bnt',
  'kxd' => 'pqw',
  'xsm' => 'alv',
  'tkq' => 'alv',
  'niy' => 'csu',
  'kca' => 'fiu',
  'rcf' => 'cpf',
  'khi' => 'mul',
  'kvr' => 'pqw',
  'ovd' => 'gmq',
  'chu' => 'zls',
  'udm' => 'fiu',
  'hif' => 'inc',
  'yid' => 'gmw',
  'azc' => 'mul',
  'qya' => 'art',
  'dob' => 'pqe',
  'snv' => 'pqw',
  'tup' => 'mul',
  'pwn' => 'fox',
  'ltz' => 'gmw',
  'wol' => 'alv',
  'loj' => 'pqe',
  'wec' => 'kro',
  'ajg' => 'alv',
  'sms' => 'smi',
  'cla' => 'roa',
  'ccp' => 'inc',
  'lil' => 'sal',
  'spo' => 'sal',
  'pel' => 'pqw',
  'twq' => 'son',
  'haa' => 'ath',
  'enb' => 'sdv',
  'nan' => 'zhx',
  'awd' => 'mul',
  'kld' => 'aus',
  'omv' => 'afa',
  'juc' => 'tuw',
  'crz' => 'hok',
  'mdf' => 'fiu',
  'glk' => 'ira',
  'mwi' => 'pqe',
  'bib' => 'dmn',
  'llp' => 'pqe',
  'orh' => 'tuw',
  'apb' => 'pqe',
  'xnd' => 'mul',
  'kaz' => 'trk',
  'mhe' => 'mkh',
  'plq' => 'ine',
  'cpg' => 'grk',
  'tet' => 'plf',
  'krx' => 'alv',
  'kax' => 'paa',
  'osa' => 'xsi',
  'plu' => 'awd',
  'cym' => 'cel',
  'grk' => 'ine',
  'mky' => 'pqe',
  'mrq' => 'pqe',
  'zum' => 'ira',
  'tsr' => 'pqe',
  'ben' => 'inc',
  'pao' => 'azc',
  'cpx' => 'zhx',
  'pri' => 'pqe',
  'yue' => 'zhx',
  'bpa' => 'pqe',
  'yav' => 'alv',
  'mft' => 'pqe',
  'akk' => 'sem',
  'fut' => 'pqe',
  'esu' => 'ypk',
  'nso' => 'bnt',
  'smy' => 'ira',
  'cus' => 'afa',
  'nie' => 'alv',
  'sag' => 'ngb',
  'ksg' => 'pqe',
  'mfq' => 'alv',
  'bph' => 'ccn',
  'gbu' => 'aus',
  'pap' => 'cpp',
  'btd' => 'btk',
  'nem' => 'pqe',
  'oka' => 'sal',
  'brf' => 'bnt',
  'lgu' => 'pqe',
  'kcm' => 'csu',
  'wdd' => 'bnt',
  'apk' => 'apa',
  'liv' => 'fiu',
  'auq' => 'pqe',
  'pmq' => 'omq',
  'blq' => 'pqe',
  'tbc' => 'pqe',
  'ven' => 'bnt',
  'sqo' => 'ira',
  'rwm' => 'bnt',
  'amw' => 'sem',
  'nnh' => 'bai',
  'mql' => 'alv',
  'koa' => 'pqe',
  'lmv' => 'pqe',
  'woe' => 'pqe',
  'khl' => 'pqe',
  'bim' => 'alv',
  'avu' => 'csu',
  'tao' => 'poz',
  'chk' => 'pqe',
  'pwg' => 'pqe',
  'yec' => 'gmw',
  'pcj' => 'mun',
  'tft' => 'paa',
  'lah' => 'inc',
  'gez' => 'sem',
  'hil' => 'phi',
  'xmz' => 'pqw',
  'jaz' => 'pqe',
  'hnj' => 'hmx',
  'nse' => 'bnt',
  'den' => 'ath',
  'inp' => 'awd',
  'tnt' => 'phi',
  'mnp' => 'zhx',
  'taw' => 'mul',
  'ili' => 'trk',
  'bmq' => 'alv',
  'smc' => 'cus',
  'clm' => 'sal',
  'iai' => 'pqe',
  'kdd' => 'aus',
  'euq' => 'mul',
  'mte' => 'pqe',
  'agq' => 'alv',
  'ser' => 'azc',
  'lce' => 'pqw',
  'szn' => 'plf',
  'ddn' => 'son',
  'kan' => 'dra',
  'szl' => 'zlw',
  'ycn' => 'awd',
  'tnx' => 'pqe',
  'bin' => 'alv',
  'gdd' => 'pqe',
  'byv' => 'bai',
  'pif' => 'pqe',
  'sjd' => 'smi',
  'ium' => 'hmx',
  'otm' => 'oto',
  'nwe' => 'bai',
  'ado' => 'alv',
  'hro' => 'cmc',
  'leu' => 'pqe',
  'lag' => 'bnt',
  'sjw' => 'alg',
  'glv' => 'cel',
  'met' => 'pqe',
  'lin' => 'bnt',
  'dnj' => 'gmq',
  'tbl' => 'phi',
  'xkg' => 'dmn',
  'tzl' => 'art',
  'inz' => 'hok',
  'wti' => 'ssa',
  'tth' => 'aav',
  'scn' => 'roa',
  'buc' => 'pqw',
  'eyo' => 'sdv',
  'pug' => 'alv',
  'ell' => 'grk',
  'loz' => 'bnt',
  'sdn' => 'roa',
  'sal' => 'mul',
  'psw' => 'pqe',
  'hak' => 'zhx',
  'peq' => 'hok',
  'crx' => 'ath',
  'wwo' => 'pqe',
  'gil' => 'pqe',
  'srr' => 'alv',
  'ldp' => 'bnt',
  'kjg' => 'mkh',
  'pia' => 'azc',
  'wyy' => 'pqe',
  'aao' => 'sem',
  'ame' => 'awd',
  'lua' => 'bnt',
  'ksf' => 'bnt',
  'miz' => 'omq',
  'mww' => 'hmx',
  'shz' => 'alv',
  'sgz' => 'pqe',
  'mlu' => 'pqe',
  'ncb' => 'mkh',
  'zbc' => 'pqw',
  'xas' => 'syd',
  'aqc' => 'ccn',
  'kzo' => 'bnt',
  'ssb' => 'pqw',
  'uhn' => 'ngf',
  'mpy' => 'pqe',
  'msq' => 'pqe',
  'wln' => 'roa',
  'lnd' => 'map',
  'sah' => 'trk',
  'jaj' => 'pqe',
  'hin' => 'inc',
  'anm' => 'tbq',
  'kxs' => 'xgn',
  'qxq' => 'trk',
  'bal' => 'ira',
  'bwo' => 'omv',
  'ttb' => 'alv',
  'orv' => 'zle',
  'tsd' => 'grk',
  'tin' => 'ccn',
  'xmf' => 'ccs',
  'eko' => 'bnt',
  'mic' => 'alg',
  'kvq' => 'kar',
  'ykm' => 'ccn',
  'bej' => 'cus',
  'urh' => 'alv',
  'dbj' => 'pqw',
  'sii' => 'mkh',
  'maf' => 'cdc',
  'beb' => 'bnt',
  'aud' => 'pqe',
  'was' => 'hok',
  'pbs' => 'omq',
  'ncc' => 'pqe',
  'jbe' => 'ber',
  'myu' => 'tup',
  'kzc' => 'alv',
  'mhs' => 'plf',
  'hsn' => 'zhx',
  'anu' => 'sdv',
  'orm' => 'cus',
  'vrs' => 'pqe',
  'beq' => 'bnt',
  'muz' => 'sdv',
  'guj' => 'inc',
  'tio' => 'pqe',
  'mzm' => 'alv',
  'mvy' => 'inc',
  'tdx' => 'pqw',
  'kkt' => 'fiu',
  'xaw' => 'azc',
  'bbj' => 'bai',
  'gui' => 'tup',
  'deu' => 'gmw',
  'hiw' => 'pqe',
  'ers' => 'tbq',
  'hmn' => 'hmx',
  'gjn' => 'alv',
  'jmc' => 'bnt',
  'tgx' => 'ath',
  'zuh' => 'paa',
  'lot' => 'sdv',
  'chg' => 'trk',
  'lui' => 'azc',
  'olr' => 'pqe',
  'mzs' => 'cpp',
  'slm' => 'pqw',
  'bre' => 'cel',
  'ibl' => 'phi',
  'cpf' => 'roa',
  'cim' => 'gmw',
  'nee' => 'pqe',
  'lbx' => 'pqw',
  'shk' => 'sdv',
  'iro' => 'mul',
  'phi' => 'pqw',
  'lra' => 'dai',
  'tfi' => 'alv',
  'tpz' => 'pqe',
  'chv' => 'trk',
  'mjt' => 'dra',
  'vao' => 'pqe',
  'pix' => 'aus',
  'tog' => 'nic',
  'jct' => 'trk',
  'tql' => 'pqe',
  'roe' => 'pqe',
  'hur' => 'sal',
  'aji' => 'pqe',
  'vma' => 'aus',
  'ats' => 'alg',
  'pra' => 'inc',
  'sqi' => 'ine',
  'ngl' => 'bnt',
  'gmw' => 'gem',
  'kpt' => 'ccn',
  'lmp' => 'alv',
  'dum' => 'gmw',
  'xpr' => 'ira',
  'bfl' => 'alv',
  'mdw' => 'bnt',
  'kia' => 'trk',
  'kyr' => 'tup',
  'rkm' => 'dmn',
  'crh' => 'trk',
  'vmk' => 'bnt',
  'tuz' => 'alv',
  'ciw' => 'alg',
  'llk' => 'pqw',
  'kmq' => 'ssa',
  'btb' => 'bnt',
  'nyf' => 'bnt',
  'dop' => 'alv',
  'lam' => 'nic',
  'pny' => 'alv',
  'ljp' => 'pqw',
  'lib' => 'pqe',
  'ddi' => 'pqe',
  'koo' => 'bnt',
  'tkl' => 'pqe',
  'alq' => 'alg',
  'mra' => 'mkh',
  'hvn' => 'poz',
  'bhc' => 'pqe',
  'tlk' => 'pqw',
  'tnz' => 'mkh',
  'oci' => 'roa',
  'ktn' => 'tup',
  'xom' => 'ssa',
  'qum' => 'myn',
  'pbg' => 'awd',
  'slv' => 'zls',
  'och' => 'zhx',
  'ndc' => 'bnt',
  'fiu' => 'urj',
  'mni' => 'sit',
  'spa' => 'roa',
  'obt' => 'cel',
  'gak' => 'paa',
  'prt' => 'mkh',
  'kcj' => 'alv',
  'owl' => 'cel',
  'tef' => 'mkh',
  'txy' => 'pqw',
  'csu' => 'ssa',
  'trn' => 'awd',
  'fra' => 'roa',
  'cel' => 'ine',
  'mmg' => 'pqe',
  'trs' => 'omq',
  'gfk' => 'pqe',
  'anw' => 'alv',
  'cnu' => 'ber',
  'mnc' => 'tuw',
  'omb' => 'pqe',
  'dtd' => 'wak',
  'tmb' => 'pqe',
  'sor' => 'cdc',
  'isl' => 'gmq',
  'sdo' => 'dai',
  'imy' => 'ine',
  'bzq' => 'pqe',
  'asb' => 'xsi',
  'vie' => 'mkh',
  'sea' => 'mkh',
  'bxe' => 'afa',
  'tah' => 'pqe',
  'hus' => 'myn',
  'grt' => 'sit',
  'ccs' => 'cau',
  'gwt' => 'inc',
  'dai' => 'pqw',
  'sdt' => 'ine',
  'nap' => 'roa',
  'alg' => 'aql',
  'ogc' => 'alv',
  'njx' => 'bnt',
  'adx' => 'tbq',
  'akb' => 'btk',
  'abr' => 'alv',
  'ces' => 'zlw',
  'poc' => 'myn',
  'tpj' => 'tup',
  'rof' => 'bnt',
  'syl' => 'inc',
  'bgc' => 'inc',
  'kmz' => 'trk',
  'snd' => 'inc',
  'lez' => 'ccn',
  'alm' => 'pqe',
  'xog' => 'bnt',
  'kma' => 'alv',
  'ney' => 'kro',
  'aln' => 'ine',
  'ude' => 'tuw',
  'kji' => 'pqe',
  'aia' => 'pqe',
  'csn' => 'sgn',
  'ipk' => 'esx',
  'vro' => 'fiu',
  'gkn' => 'alv',
  'lcl' => 'map',
  'klv' => 'pqe',
  'bbh' => 'mkh',
  'lgl' => 'pqe',
  'ile' => 'art',
  'lcf' => 'pqw',
  'btr' => 'pqe',
  'sxn' => 'phi',
  'kau' => 'ssa',
  'sdc' => 'roa',
  'skf' => 'tup',
  'mme' => 'pqe',
  'dml' => 'inc',
  'cba' => 'mul',
  'yka' => 'pqw',
  'gro' => 'tbq',
  'alu' => 'pqe',
  'nss' => 'pqe',
  'nrc' => 'cel',
  'kfa' => 'dra',
  'lre' => 'iro',
  'bnn' => 'fox',
  'xlc' => 'ine',
  'pli' => 'pra',
  'ank' => 'cdc',
  'xbc' => 'ira',
  'yej' => 'grk',
  'ita' => 'roa',
  'cji' => 'ccn',
  'cia' => 'pqw',
  'wls' => 'pqe',
  'mek' => 'pqe',
  'del' => 'alg',
  'frp' => 'roa',
  'ebu' => 'bnt',
  'kwd' => 'pqe',
  'xmm' => 'cpp',
  'sjo' => 'tuw',
  'pmo' => 'hok',
  'ign' => 'awd',
  'apr' => 'pqe',
  'xlo' => 'alg',
  'cgg' => 'bnt',
  'knf' => 'alv',
  'twp' => 'pqe',
  'ree' => 'pqw',
  'wlc' => 'bnt',
  'otk' => 'trk',
  'btk' => 'pqw',
  'alo' => 'plf',
  'ngc' => 'bnt',
  'tyu' => 'bnt',
  'baa' => 'pqe',
  'tuf' => 'cba',
  'coz' => 'omq',
  'ntm' => 'alv',
  'pyu' => 'fox',
  'kat' => 'ccs',
  'aca' => 'awd',
  'pms' => 'roa',
  'lbw' => 'pqw',
  'ztq' => 'omq',
  'sin' => 'inc',
  'goa' => 'dmn',
  'cor' => 'cel',
  'rut' => 'ccn',
  'fkv' => 'fiu',
  'poo' => 'hok',
  'ido' => 'art',
  'ngb' => 'alv',
  'quc' => 'myn',
  'nyn' => 'bnt',
  'mon' => 'xgn',
  'hac' => 'ira',
  'sgs' => 'bat',
  'tht' => 'ath',
  'ils' => 'sgn',
  'bkm' => 'alv',
  'xpi' => 'cel',
  'svx' => 'bat',
  'egl' => 'roa',
  'lkn' => 'pqe',
  'hup' => 'ath',
  'bqh' => 'tbq',
  'oog' => 'fiu',
  'gud' => 'kro',
  'onu' => 'pqe',
  'smr' => 'pqw',
  'btm' => 'btk',
  'xwc' => 'xsi',
  'acr' => 'myn',
  'lpa' => 'pqe',
  'tpc' => 'omq',
  'urd' => 'inc',
  'mml' => 'mkh',
  'par' => 'azc',
  'kak' => 'phi',
  'kos' => 'pqe',
  'ppi' => 'hok',
  'lky' => 'sdv',
  'ist' => 'roa',
  'sqr' => 'sem',
  'nua' => 'pqe',
  'bwd' => 'pqe',
  'abw' => 'ira',
  'udu' => 'ssa',
  'mna' => 'pqe',
  'san' => 'pra',
  'bch' => 'pqe',
  'usp' => 'myn',
  'lbj' => 'sit',
  'jah' => 'mkh',
  'bex' => 'csu',
  'jav' => 'pqw',
  'sto' => 'xsi',
  'dtp' => 'pqw',
  'tsj' => 'sit',
  'epo' => 'art',
  'suk' => 'bnt',
  'mkh' => 'aav',
  'nok' => 'sal',
  'urw' => 'bnt',
  'mye' => 'bnt',
  'olt' => 'bat',
  'tpl' => 'omq',
  'tuy' => 'sdv',
  'nuw' => 'pqe',
  'tbj' => 'pqe',
  'egy' => 'afa',
  'bos' => 'zls',
  'ncn' => 'pqe',
  'mox' => 'pqe',
  'gni' => 'aus',
  'ssn' => 'cus',
  'rom' => 'inc',
  'zwa' => 'omv',
  'lbn' => 'mkh',
  'bhb' => 'inc',
  'dws' => 'art',
  'pan' => 'inc',
  'abb' => 'bnt',
  'fit' => 'fiu',
  'vnk' => 'pqe',
  'sel' => 'syd',
  'otd' => 'pqw',
  'myl' => 'pqw',
  'fab' => 'cpp',
  'kjk' => 'pqw',
  'wen' => 'zlw',
  'mrb' => 'pqe',
  'fmp' => 'bai'
};
#-*-perl-*-

=head1 SUBROUTINES

=head2 @langcodes = language_group( $groupcode )

Returns a list of language codes within the given language group.

=cut


sub language_group{
    if (exists $$LanguageGroup{$_[0]}){
	return @{$$LanguageGroup{$_[0]}};
    }
    print STDERR "unknown language group $_[0]\n";
    return ();
}


=head2 @parentcode = language_group( $langcode )

Returns the parent language code for the given language.

=cut


sub language_parent{
    if (exists $$LanguageParent{$_[0]}){
	return $$LanguageParent{$_[0]};
    }
    print STDERR "no parent found for '$_[0]'\n";
    return undef;
}

1;

